### ISSUE TITLE
This is a sample ticket

### ISSUE THREAD

**Issue by testshreyas123** [orgshreyas2/test2#11]
Freshdesk Ticket ID: 1 <br/> Freshdesk Ticket Agent: Unassigned<br/>Freshdesk Ticket Agent Email: Unassigned<br/>Ticket Priority: Low<br/>Freshdesk Ticket Description:<br/><div>This is a sample ticket, feel free to delete it.</div> <br/>

**Comment by testshreyas123** [comment]
Comment added by Agent Support in Freshdesk ticket id 1:<br/><div>Linked ticket to issue <a href="https://github.com/orgshreyas2/test1/issues/2"> #2 </a> in GitHub repository orgshreyas2/test1</div>

**Comment by testshreyas123** [comment]
Comment added by Agent Support in Freshdesk ticket id 1:<br/><div style="font-size: 13px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">

<div>test note should be added when the issue is created.</div>

</div>

**Comment by testshreyas123** [comment]
Agent Support linked Freshdesk ticket 3 to this issue

**Comment by shreyas-srinivas** [comment]
Comment should appear in ticket 1
![testimg](https://cloud.githubusercontent.com/assets/11406399/9575305/399dd4fe-4fec-11e5-9882-64e00346b772.png)

**Comment by shreyas-srinivas** [comment]
Comment should appear in ticket 1
![testimg](https://cloud.githubusercontent.com/assets/11406399/9575305/399dd4fe-4fec-11e5-9882-64e00346b772.png)

**Comment by shreyas-srinivas** [comment]
Comment should appear in ticket 1
![testimg](https://cloud.githubusercontent.com/assets/11406399/9575305/399dd4fe-4fec-11e5-9882-64e00346b772.png)

**Comment by testshreyas123** [comment]
etstasd adad a fad

**Comment by testshreyas123** [comment]
notify agent with this comment.
