### ISSUE TITLE
Test 1- title edit

### ISSUE THREAD

**Issue by testshreyas123** [orgshreyas2/test2#8]
Freshdesk Ticket ID: 13 <br/> Freshdesk Ticket Agent: Unassigned<br/>Freshdesk Ticket Agent Email: Unassigned<br/>Ticket Priority: Low<br/><div style="font-size: 13px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">

<div>Test properly</div>

</div> <br/>

**Comment by testshreyas123** [comment]
Support linked Freshdeskticket #14 to this issue

**Comment by testshreyas123** [comment]
Comment added by Support in Freshdesk ticket id 13:<br/><div style="font-size: 13px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">

<div>this comment should get added inot github with the attachment</div>

</div>

Attachments :
1. <a href='http://shreyas.ngrok.com/helpdesk/attachments/10'>Screen Shot 2015-07-09 at 1.44.20 pm.png</a>

**Comment by shreyas-srinivas** [comment]
This comment should get added into fd

**Comment by testshreyas123** [comment]
Support <Agent}> unlinked Freshdesk ticket 14 from this issue

**Comment by testshreyas123** [comment]
Support <Agent}> linked Freshdesk ticket 14 to this issue

**Comment by testshreyas123** [comment]
Support <Agent> unlinked Freshdesk ticket 14 from this issue

**Comment by shreyas-srinivas** [comment]
<h2>asdad</h2>

**Comment by shreyas-srinivas** [comment]
<asd>

**Comment by shreyas-srinivas** [comment]
<div style="text:bold">
asdad
</div>

**Comment by shreyas-srinivas** [comment]
asdad<div style="padding: 20px" > test</div>

**Comment by shreyas-srinivas** [comment]
<h2 style="color:blue;margin-left:30px;">This is a heading.</div>

**Comment by testshreyas123** [comment]
Support <Agent> linked Freshdesk ticket 14 to this issue

**Comment by shreyas-srinivas** [comment]
<h2 style="color:blue;margin-left:30px;">This is a heading.</div>

<script type="javascript" >
alert("asdsfg");
</script>

**Comment by testshreyas123** [comment]
Comment added by Support in Freshdesk ticket id 14:<br/><div style="font-size: 13px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">

<div>&lt;h2 style="color:blue;margin-left:30px;"&gt;This is a heading.&lt;/div&gt;</div>

<div>&lt;script type="javascript" &gt;</div>

<div>alert("asdsfg");</div>

<div>&lt;/script&gt;</div>

</div>

**Comment by shreyas-srinivas** [comment]
![screen shot 2015-07-09 at 1 44 20 pm](https://cloud.githubusercontent.com/assets/11406399/9356083/f198e44a-469b-11e5-892c-af50a9f63d9a.png)

**Comment by shreyas-srinivas** [comment]
comment with 2 attachemtns
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356330/c28f7554-469d-11e5-90db-7b00e9f1f545.png)
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356335/cae07276-469d-11e5-850e-670094b0928b.png)

eqweq

![signup-msg](https://cloud.githubusercontent.com/assets/11406399/9356338/cf3ed7c2-469d-11e5-9f52-bab0672aa977.png)

final

**Comment by shreyas-srinivas** [comment]
comment with 2 attachemtns
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356330/c28f7554-469d-11e5-90db-7b00e9f1f545.png)
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356335/cae07276-469d-11e5-850e-670094b0928b.png)

eqweq

![signup-msg](https://cloud.githubusercontent.com/assets/11406399/9356338/cf3ed7c2-469d-11e5-9f52-bab0672aa977.png)

final

**Comment by shreyas-srinivas** [comment]
comment with 2 attachemtns
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356330/c28f7554-469d-11e5-90db-7b00e9f1f545.png)
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356335/cae07276-469d-11e5-850e-670094b0928b.png)

eqweq

![signup-msg](https://cloud.githubusercontent.com/assets/11406399/9356338/cf3ed7c2-469d-11e5-9f52-bab0672aa977.png)

final2

**Comment by shreyas-srinivas** [comment]
comment with 2 attachemtns
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356330/c28f7554-469d-11e5-90db-7b00e9f1f545.png)
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356335/cae07276-469d-11e5-850e-670094b0928b.png)

eqweq

![signup-msg](https://cloud.githubusercontent.com/assets/11406399/9356338/cf3ed7c2-469d-11e5-9f52-bab0672aa977.png)

final
2

**Comment by shreyas-srinivas** [comment]
![test](http://shreyas.ngrok.com/helpdesk/attachments/10)

**Comment by shreyas-srinivas** [comment]
comment with 2 attachemtns
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356330/c28f7554-469d-11e5-90db-7b00e9f1f545.png)
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356335/cae07276-469d-11e5-850e-670094b0928b.png)

eqweq

![signup-msg](https://cloud.githubusercontent.com/assets/11406399/9356338/cf3ed7c2-469d-11e5-9f52-bab0672aa977.png)

final
3

**Comment by shreyas-srinivas** [comment]
comment with 2 attachemtns
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356330/c28f7554-469d-11e5-90db-7b00e9f1f545.png)
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356335/cae07276-469d-11e5-850e-670094b0928b.png)

eqweq

![signup-msg](https://cloud.githubusercontent.com/assets/11406399/9356338/cf3ed7c2-469d-11e5-9f52-bab0672aa977.png)

final
4

**Comment by shreyas-srinivas** [comment]
comment with 2 attachemtns
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356330/c28f7554-469d-11e5-90db-7b00e9f1f545.png)
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356335/cae07276-469d-11e5-850e-670094b0928b.png)

eqweq

![signup-msg](https://cloud.githubusercontent.com/assets/11406399/9356338/cf3ed7c2-469d-11e5-9f52-bab0672aa977.png)

final
5

**Comment by testshreyas123** [comment]
Agent Support unlinked Freshdesk ticket 14 from this issue

**Comment by testshreyas123** [comment]
Agent Support linked Freshdesk ticket 13 to this issue

**Comment by shreyas-srinivas** [comment]
comment with 2 attachemtns
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356330/c28f7554-469d-11e5-90db-7b00e9f1f545.png)
![screen shot 2015-07-09 at 1 44 22 pm](https://cloud.githubusercontent.com/assets/11406399/9356335/cae07276-469d-11e5-850e-670094b0928b.png)

eqweq

![signup-msg](https://cloud.githubusercontent.com/assets/11406399/9356338/cf3ed7c2-469d-11e5-9f52-bab0672aa977.png)

final
5

**Comment by testshreyas123** [comment]
Comment added by Agent Support in Freshdesk ticket id 14:<br/><div style="font-size: 13px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;">

<div>dadadacassaxax</div>

</div>

**Comment by testshreyas123** [comment]
Agent Support unlinked Freshdesk ticket 14 from this issue

**Comment by shreyas-srinivas** [comment]
test agent email notification
